import Head from 'next/head'
import Hero from "@/components/Hero/Hero";
import Slider from "@/components/Slider/Slider";
import { SliderData } from "@/components/Slider/SliderData";
import Instagram from "@/components/Instagram/Instagram";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title> Photo App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" message/>
      </Head>
        <Hero
            heading='Photography'
            message='Photography is the art, application,
            and practice of creating durable images by recording light, either
            electronically by means of an image sensor,
            or chemically by means of a light-sensitive
            material such as photographic film.'
        />
      <Slider slides={SliderData} />
      <Instagram  />
    </div>
  )
}

